version: "2.4"

services:
  gateway:
    image: kkchaulagain/kyc_gateway
    container_name: kyc_gateway
    volumes:
      - ./:/var/www/html
    ports:
      - "2060:80"
  auth:
    image: kkchaulagain/kyc_auth
    container_name: kyc_auth
    volumes:
      - ./:/var/www/html
    ports:
      - "2061:80"
